project:
  type: website

website:
  title: "Matthew Hlina"
  image: "/img/me.png"
  
  navbar:
    background: "#01998D"
    left:
      - text: "Academic Projects"
        menu:
          - text: Polynomial Effects
            href: projects/fertility/index.qmd
          - text: Logrithmic Transformations
            href: projects/wine/index.qmd
          - text: Logistic Regression
            href: projects/ssm/index.qmd
          - text: Unconditional Longitudinal Mixed-Effects Models
            href: projects/nhl/index.qmd
      - text: "Research Experience"
        href: research/index.qmd
            
    right: 
      - text: "About"
        href: about/index.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-hlina-1aa167275
      - icon: mortarboard
        aria-label: google scholar
        href: https://scholar.google.com/citations?user=q6zxiHYAAAAJ&hl=en&oi=ao
      - icon: github
        href: https://github.com/matthewhlina
      - icon: envelope
        aria-label: email
        href: "mailto:hlina002@umn.edu"

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-cap-location: bottom
    link-external-newwindow: true

execute: 
  freeze: auto

editor: visual

