---
title: "About"
mainfont: Calibri
---

I am a mixed methods researcher with my most recent experience at the University of Minnesota in the sport management program and [Global Institute for Responsible Sport Organizations](https://girso.umn.edu). I grew up in a modest home in the unincorporated town of South Range, Wisconsin and spent my years from birth to 18 under the same roof. Living in a place where my friends lived 30 minutes away made for some social challenges as youngster, especially in the summer months, but the bountiful solo time aided to develop a curiosity with my surroundings and an enjoyment in attempting to understand. As such, I've always enjoyed schooling and found comfort in teaching others. I've continued both my education and interested in teaching through all of my academic, volunteer, and practical experiences and have directed my focuses towards improving the health and wellness of individuals, society, and the natural world. My interests have led to the development of skills in qualitative and quantitative research methods, including technical experience with the software programs R, Quarto, Qualtrics, and NVIVO and soft-skill such as public speaking, relationship-building, and teamwork. I am interested in continuing to utilize and grow these skills to contribute to solving real-world problems related to human, societal, and environmental health.

I've developed qualitative research skills through research projects associated with the [Global Institute for Responsible Sport Organizations](https://girso.umn.edu) at the University of Minnesota, including survey design, interview protocols, and qualitative data analysis.  professional sport corporate social responsibility, consumer behavior, organizational theory, microbiology, and environmental biology. The majority of my qualitative research experience has been cultivated during my time as a part of the 