{
  "hash": "c3b60d9af4e36004a4ecedc4de8a5b91",
  "result": {
    "markdown": "---\ntitle: \"Unconditional Longitiduinal Mixed-Effects Models\"\nformat: \n  html:\n    fig-width: 12\n    fig-height: 9\neditor: visual\nexecute: \n  echo: false\ncode-tools: true\n---\n\n\n## Fan Cost Index of Attending NHL Games\n\n[CSV](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/data/nhl.csv)\n\n[Codebook](http://zief0002.github.io/bespectacled-antelope/codebooks/nhl.html)\n\n### Investigating the Relationship\n\nThe Fan Cost Index (FCI) is an index used to determine the cost of attendance to a sporting event for a family of four. It is calculated by summing the prices of four average-price tickets, two small draft beers, four small soft drinks, four regular-size hot dogs, parking for one car, two game programs, and two least-expensive, adult-size adjustable caps, for a season. \n\nThis project assessed the longitudinal variation in cost of attending an NHL game from 2002-2014 by using FCI to denote cost (no data from 2012 due to lockout). Here is a figure displaying trend lines for the relationship between FCI and year for each NHL team and an average growth trend line is displayed in bold.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Cost of attending a NHL game (FCI) over time for each NHL team. The black line represents the average cost of attending NHL games.](index_files/figure-html/fig-spaghetti-1.png){#fig-spaghetti width=1152}\n:::\n:::\n\n\nThe average growth trendline is positive and appears to be linear, although there may be evidence that suggests a quadratic relationship between FCI and year. \n\n### Creating and Comparing Models\n\nThree models will be considered in this analysis: a) an uncondiational random intercepts model; b) an unconditional linear growth model; and c) an unconditional quadratic growth model. Here is a table of the unstandardized coefficients and standard errors for these models.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\nTable 1. Unstandardized Coefficients and Confidence Intervals for a Series of LMER Models Fitted to Estimate FCI of NHL Games\n=====================================================================================\n                                  Model A            Model B            Model C      \nTeam                                                  10.138             5.205       \n                                                 (8.867, 11.408)     (0.847, 9.564)  \n                                                                                     \nYear                                                                     0.413       \n                                                                     (0.064, 0.763)  \n                                                                                     \nYear(Squared)                     299.881            236.580            244.821      \n                             (281.121, 318.642) (216.925, 256.235) (224.052, 265.590)\n                                                                                     \n-------------------------------------------------------------------------------------\nLevel-2 Variance (Intercept)      2428.05            2398.24            2385.28      \nLevel-1 Variance                  3478.38            1727.95            1691.46      \nAICc                              3034.34            2866.48            2863.25      \n=====================================================================================\n                                                                                     \n```\n:::\n:::\n\n\nModel C has the most empirical support for representing the data (AICc = 2385.28). Below is the written equation for this model.\n\n$$\n\\begin{split}\n\\hat{\\mathrm{FCI}_{i}} &= 244.82+ 5.21(\\mathrm{Year-2002}_{ij}) + 0.41(\\mathrm{Year-2002}_{ij})^2 +\\mathrm{b_{0j}}\n\\end{split}\n$$\n\n### Interpretting Model 3\n\nThe variation between teams (58.50%) accounts for more variation than the variation within a team (41.50%). In practical terms, this means that a team's FCI in 2002 (the y-intercept) has a larger impact on the FCI of a given year than the rate of change in FCI of a team (the slope). \n\nThe predicted average FCI for all teams at the initial measurement occasion (in 2002) is 244.82.\nEach subsequent year is associated with an increase in FCI by at least 5.61 points. The effect of year on FCI increases over time.\n\nAdditionally, here is a figure that presents our model as well as a trend line that represents the FCI for the Minnesota Wild NHL team.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Unconditional quadratic growth models showing the relationship between year and NHL fan cost index. The green curve shows the predicted cost of attending a Minnesota Wild game, whereas the red curve shows the predicted cost of attending any NHL game, on average.](index_files/figure-html/fig-fits-1.png){#fig-fits width=1152}\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}