{
  "hash": "7d3c67cf2b12380b7148863878d6be4e",
  "result": {
    "markdown": "---\ntitle: \"Logistic Regression\"\nformat: \n  html:\n    fig-width: 12\n    fig-height: 9\neditor: visual\nexecute: \n  echo: false\ncode-tools: true\n---\n\n\n## The Effect of Religion on Personal Support for Same-Sex Marriage\n\nReligious service attendance and type of denomination are thought to be associated with support for or against same-sex marriage (SSM). To understand more about this relationship, 1746 participants were recruited to take part in a survey that inquired about their service attendance frequency on a Likert-scale (0 = never; 4 = every week) and support for SSM (0 = no; 1 = yes). In addition to this information, the survey asked about participants' age, denomination, sex (0 = male; 1 = female), and whether they had friends or family that are LGBTQ+ (0 = no; 1 = yes) as a way to collect information about covariates in the primary relationship being investigated. More information about these variables can be attained by looking at the codebook linked below.\n\n[CSV](https://raw.githubusercontent.com/zief0002/bespectacled-antelope/main/data/same-sex-marriage.csv)\n\n[Codebook](http://zief0002.github.io/bespectacled-antelope/codebooks/same-sex-marriage.html)\n\n### Investigating the Relationship\nThe figure below was created in order to understand the relationship between religious service attendance and support for SSM. While respondents could only answer no (0) or yes (1) to whether they support SSM, in the figure, these data points are dispersed above and below 0 and 1 on the y-axis to demonstrate the number of responses associated with each level of religious service attendance (i.e., more dots corresponds to more responses). To reiterate, even though these data points may appear to be another number in the figure, they are always actually either 0 or 1. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatterplot with smoother showing the relationship between religious service attendance and support for SSM where support for SSM is 1 and support against SSM is 0.](index_files/figure-html/fig-scatter-1.png){#fig-scatter width=1152}\n:::\n:::\n\n\nAccording to this figure, religious service attendance appears to have a negative effect on support for SSM. While religious service attendance appears to be continuous, the relationship between religious service attendance and support for SSM looks to be non-linear, meaning a transformation of one or both of these variables is necessary to carry out a regression. \n\n### Creating and Interpretting Model 1\n\nDichotomous response variables, or those bounded between 0 and 1, require transformation to adjust the Sigmoid curve associated with these variable so that the linearity assumption of regression is met. The logistic function is an effective function to use to transform Sigmoid curves to be linear; therefore, support for SSM was transformed using a logistic transformation. Additionally, the rule of the bulge suggests an upward transformation of the response variable may help with the linearity assumption. After applying these transformations, a regression was carried out ($\\hat{\\pi_i}$ is the probability of supporting of SSM in the equation below).\n\n$$\n\\begin{split}\n\\mathrm{Model~1}:~ \\mathrm{ln(\\frac{\\hat{\\pi_i}}{1+\\hat{\\pi_i}})} &= -0.19 + 0.14(\\mathrm{Attendance}_i) - 0.12(\\mathrm{Attendance}_i^2) \\\n\\end{split}\n$$ \n\nThe **predicted** log-odds, odds, and probability of a person who supports SSM and doesn't attend religious service can all be obtained from this equation. \n\n$\\mathrm{log\\mbox{-}odds} = -0.19$\n\n$\\mathrm{odds} = 0.83$\n\n$\\mathrm{probability} = 0.45$\n\nThese predicted metrics suggest that it is more likely that a person, who does not attend religious services, will not support SSM. Based on the coefficients associated with religious service attendance, attendance is generally associated with a decreased likelihood of supporting SSM and that this effect is stronger as attendance increases, although support for SSM marginally increases for people who attend religious service a few times a year (Attendance = 1).\n\n### Investigating Additional Models\n\nFrom Model 1, four additional models were made by including covariates according to correlations among covariates and between covariates and the outcome variable. Covariates included in the models were introduced in the first paragraph of this project. All models were placed into a table to compare and determine which most appropriately represents the data.\n\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;color: #000000;border-top: 1px solid #000000;\">\n<caption>Table 1. Five candidate models predicting variation in the log-odds of supporting same-sex marriage. The denomination predictor was dummy coded (Catholic, Jewish, and Other), with Protestant as the reference group.</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</th>\n<th style=\"padding-left: 20px;padding-right: 20px;\">Model 1</th>\n<th style=\"padding-left: 20px;padding-right: 20px;\">Model 2</th>\n<th style=\"padding-left: 20px;padding-right: 20px;\">Model 3</th>\n<th style=\"padding-left: 20px;padding-right: 20px;\">Model 4</th>\n<th style=\"padding-left: 20px;padding-right: 20px;\">Model 5</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 20px;padding-right: 20px;\">Attendance_L</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.14</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.14</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.04</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.03</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.12)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.13)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.13)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.13)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Attendance_Q</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.12</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.12</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.07</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.07</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.03)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.03)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.03)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.03)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Catholic</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.77</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.66</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.50</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.50</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.14)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.14)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.15)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.15)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Jewish</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.38</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.25</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.07</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.06</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.13)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.13)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.14)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.14)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Other</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">2.30</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">1.93</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">1.76</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">1.76</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.52)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.53)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.55)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.55)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Age</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.02</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.03</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.00)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.00)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Friends</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.76</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.73</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.11)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.11)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Female</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.33</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.11)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">Intercept</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.19</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-1.07</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">-0.53</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.36</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.22</td>\n</tr>\n<tr>\n<td style=\"padding-left: 20px;padding-right: 20px;\">&nbsp;</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.10)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.10)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.14)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.24)</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">(0.25)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 20px;padding-right: 20px;\">AICc</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">2126.47</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">2196.62</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">2085.59</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">1967.75</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">1959.48</td>\n</tr>\n<tr style=\"border-bottom: 1px solid #000000;\">\n<td style=\"padding-left: 20px;padding-right: 20px;\">R2</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.05</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.02</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.07</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.12</td>\n<td style=\"padding-left: 20px;padding-right: 20px;\">0.12</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"6\">The $R^2$ value is based on the proportion of reduced deviance from the intercept-only model.</td>\n</tr>\n</tfoot>\n</table>\n\n\nModel 5 was the most appropriate model for the data (AICc = 1959.48; ${R}^2$ = 0.12), although Model 4 received some empirical support (`&#916;AICc = 8.27`{=html}).\n\n$$\n\\begin{align}\n\\mathrm{Model~5}: \\mathrm{ln(\\frac{\\hat{\\pi_i}}{1+\\hat{\\pi_i}})} &= 0.22 - 0.03(\\mathrm{Attendance}_i) - 0.07(\\mathrm{Attendance}_i^2) + 0.50(\\mathrm{Catholic}_i)\n\\nonumber \\\\\n&\\quad + 0.06(\\mathrm{Jewish}_i) + 1.76(\\mathrm{Other}_i) - 0.03(\\mathrm{Age}_i) + 0.73(\\mathrm{Friends}_i) + 0.33(\\mathrm{Female}_i)\n\\end{align}\n$$ \n\n### Interpretting Model 5\n\nThe following figure presents the predicted probabilities, according to Model 5, of supporting SSM for a 47.7 man (for the mean male age in the sample) who does not have any friends or family that are LGBTQ+.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Generalized linear models showing the relationship between religious service attendance and support for same-sex marriage, for male respondents of mean age (47.7 in the dataset) who do not have LGBTQ+ friends.](index_files/figure-html/fig-fits-1.png){#fig-fits width=1152}\n:::\n:::\n\n\nSimilar to Model 1, an increase in religious services attendance is associated with a decreased predicted probability of supporting SSM, and this negative effect increases as attendance frequency increases. Of all religious denominations in this study, people who identify as protestant have the lowest predicted probability of supporting SSM and people who are Jewish have the highest predicted probability. This is consistent across all levels of service attendance.\n\nPeople who have friends or family members that are LGBTQ+ have a higher predicted probability of supporting SSM than those who do not, and women have a higher predicted probability of supporting SSM than men. Attending religious service is associated with a decreased probability of supporting SSM, and this effect of religious service attendance becomes stronger as attendance frequency increases (i.e., the more frequent a person attends religious services, the less likely they support SSM).\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}