on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
         
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Set up R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::bookdown
            any::broom
            any::broom.mixed
            any::corrr
            any::downlit
            any::dplyr
            any::ggtext
            any::ggplot2
            any::gt
            any::here
            any::kableExtra
            any::knitr
            any::lme4
            any::lmtest
            any::patchwork
            any::performance
            any::purrr
            any::readr
            any::rmarkdown
            any::rvest
            any::scales
            any::stargazer
            any::texreg
            any::tibble
            any::tidyr 
            any::tidyverse
            any::tinytex
            any::xml2
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
